// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-usability/AccessibleReadable.tsx": () => import("../components/mockups/dashboard-usability/AccessibleReadable.tsx"),
  "./components/mockups/dashboard-usability/InformationClarity.tsx": () => import("../components/mockups/dashboard-usability/InformationClarity.tsx"),
  "./components/mockups/dashboard-usability/InteractionAffordance.tsx": () => import("../components/mockups/dashboard-usability/InteractionAffordance.tsx")
};
